"""add reviews

Revision ID: 01cff8580add
Revises: 97d6eba51126
Create Date: 2025-03-07 00:06:37.643356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '01cff8580add'
down_revision: Union[str, None] = '97d6eba51126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('book_uid', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'books', ['book_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'review_text')
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'book_uid')
    # ### end Alembic commands ###
